import {
  WORLD_LORE_FORMAT,
  WORLD_LORE_VERSION,
  type WorldLorebookV1,
} from "../schema.ts";

export const CODA_WORLD_ID = "coda";

export const CODA_WORLD_LORE: WorldLorebookV1 = {
  format: WORLD_LORE_FORMAT,
  version: WORLD_LORE_VERSION,
  worldId: CODA_WORLD_ID,
  revision: "0.1.0",
  entries: [
    {
      id: "setting-foundation",
      title: "Coda at the first age of steam",
      content: "Coda's world is a materially grounded, rainbound setting at the beginning of industrial transformation. Cozy mystery, patient companionship, firelight, old books, and practical comforts coexist with dangerous new engines and an older runic craft that nobody fully understands. Most life remains pre-industrial: travel is by foot, cart, or working animal; messages go by courier; homes use hearths or stoves; and nights are lit by candles, oil lamps, moonlight, or not at all. The world's name and the city's name and government remain unknown.",
      triggers: [],
      priority: "mandatory",
      rating: "general",
      constantActivation: true,
      locationTags: [],
      sceneTags: [],
      sourceRefs: ["docs/coda-world-bible.md#Core-Promise", "docs/coda-world-bible.md#Everyday-Life", "docs/coda-world-bible.md#Open-Questions"],
    },
    {
      id: "technology-limits",
      title: "Technology and industrial limits",
      content: "Reliable steam power and consistently refined copper and brass are recent achievements. Useful engines are enormous, expensive, stationary installations used for mine pumps, drainage, a few experimental mills, specialized workshops, or institutional display. Boilers demand building-scale staffing and care. Steam locomotives, compact or personal engines, mechanical servants, powered armor, airships, and streets of automated devices do not exist. Copper and brass remain costly and politically important for corrosion-resistant pipes, heat-transfer parts, valves, fittings, gauges, instruments, fine tools, and precise engraved plates. Counterfeit fittings, stolen old copper, guarded alloys, inconsistent standards, and pressure failures are credible dangers; mature steampunk ornament and ubiquitous machinery are not.",
      triggers: ["steam", "engine", "boiler", "gauge", "copper", "brass", "machine", "technology", "industrial"],
      priority: "mandatory",
      rating: "general",
      constantActivation: true,
      locationTags: [],
      sceneTags: ["industrial"],
      sourceRefs: ["docs/coda-world-bible.md#Technology-Level", "docs/coda-world-bible.md#Copper-and-Brass", "docs/coda-world-bible.md#Industrial-Restraint"],
    },
    {
      id: "runic-craft-limits",
      title: "Old runic craft and its limits",
      content: "Runes are real and can create repeatable effects under some conditions, but they are an exacting material craft rather than spoken or arbitrary spellcasting. Surviving work is usually bound to a material, object, structure, boundary, or narrow purpose. Shape, order, material, damage, and placement matter; copying a visible mark need not reproduce its effect, and partial sequences may be inert, altered, or dangerous. Interpretations are incomplete and contradictory. Runes never solve a problem without cost, conditions, and consequences. Some old structures react near operating steam engines, but whether heat, pressure, vibration, refined metal, disturbed foundations, reproduced relationships, coincidence, or different causes explain those events remains unresolved.",
      triggers: ["rune", "runic", "symbol", "inscription", "mark", "seal", "boundary stone"],
      priority: "mandatory",
      rating: "general",
      constantActivation: true,
      locationTags: [],
      sceneTags: ["runes", "investigation"],
      sourceRefs: ["docs/coda-world-bible.md#Old-Runic-Craft", "docs/coda-world-bible.md#Steam-and-Runes"],
    },
    {
      id: "collar-mystery-boundaries",
      title: "The rune collar mystery",
      content: "Coda's dark collar permits meaningful communication with people and deepens her understanding of human language. Its turquoise marks are runic but match no complete surviving alphabet; its integrated red diamond pendant is not a later decorative tag. The collar consistently recognizes Coda, can be weakened or interrupted by damage, and was repaired before the familiar Moonlit Study scenario by someone she trusts. Its maker, age, origin, mechanism, intended wearer, pendant purpose, and the existence or history of other collars are unknown. Evidence must be specific, incomplete, and open to competing interpretations. No expert, prophecy, villain, inscription, reaction, or single clue may settle the mystery prematurely. The collar is Coda's to wear, refuse to expose, or permit others to examine.",
      triggers: ["collar", "pendant", "turquoise", "speech", "translate", "repair", "Coda's origin"],
      priority: "mandatory",
      rating: "general",
      constantActivation: true,
      locationTags: [],
      sceneTags: ["collar mystery", "runes"],
      sourceRefs: ["docs/coda-world-bible.md#The-Rune-Collar", "docs/coda-world-bible.md#Mystery-Discipline", "docs/coda-world-bible.md#Continuity-Rules"],
    },
    {
      id: "location-moonlit-study",
      title: "The Moonlit Study",
      content: "The Moonlit Study is Coda's emotional home inside an older building of unresolved history. It is a warm room with dark carved shelves, old books, a broad fireplace, rain-marked windows, a sturdy rug, and a worktable for damaged objects. It supports safe sleep, shared stories, quiet conversation, domestic rituals, incomplete records, clue examination, and a contrast among old wood, old runes, and new brass instruments. Its legal ownership can vary with the player's role. It is not a magical archive and does not contain every answer; its collection inherits the interests and limits of whoever assembled it.",
      triggers: ["Moonlit Study", "study", "fireplace", "shelves", "home"],
      priority: "high",
      rating: "general",
      constantActivation: false,
      locationTags: ["moonlit-study"],
      sceneTags: ["home", "quiet", "clue examination"],
      sourceRefs: ["docs/coda-world-bible.md#Home-Base-The-Moonlit-Study"],
    },
    {
      id: "location-first-pumping-house",
      title: "The First Pumping House",
      content: "A celebrated municipal steam engine lifts water from a flood-prone district. Crowds once gathered to hear it start, while its operators now conceal how often gauges behave strangely after midnight. The site supports mechanical danger, civic pride, buried runes, pressure both physical and political, and sounds Coda notices before others. Strange gauges are established; their cause is not.",
      triggers: ["First Pumping House", "pumping house", "municipal pump", "flood district"],
      priority: "normal",
      rating: "general",
      constantActivation: false,
      locationTags: ["first-pumping-house"],
      sceneTags: ["industrial", "civic mystery"],
      sourceRefs: ["docs/coda-world-bible.md#The-First-Pumping-House"],
    },
    {
      id: "location-coppersmith-lane",
      title: "Coppersmith Lane",
      content: "Coppersmith Lane is a crowded row of workshops where old metalworkers, new engineers, engravers, counterfeiters, and scrap dealers compete for refined metal. Each doorway carries a different hammer rhythm and opinion about runes. It is suited to repair work, stolen artifacts, false fittings, industrial rivalries, conflicting expertise, and sensory overload.",
      triggers: ["Coppersmith Lane", "coppersmith", "metalworker", "foundry", "scrap dealer"],
      priority: "normal",
      rating: "general",
      constantActivation: false,
      locationTags: ["coppersmith-lane"],
      sceneTags: ["workshops", "industrial", "repair"],
      sourceRefs: ["docs/coda-world-bible.md#Coppersmith-Lane"],
    },
    {
      id: "location-bookbinders-court",
      title: "Bookbinder's Court",
      content: "Bookbinder's Court is a sheltered courtyard of paper sellers, binders, copyists, small kitchens, and rented rooms. News moves through marginal notes, borrowed books, mistaken deliveries, and talk over cooling bread. Its mysteries favor domestic routine, damaged records, familiar scents, neighborhood knowledge, practical kindness, and clues whose importance emerges slowly.",
      triggers: ["Bookbinder's Court", "bookbinder", "binder", "copyist", "paper seller"],
      priority: "normal",
      rating: "general",
      constantActivation: false,
      locationTags: ["bookbinders-court"],
      sceneTags: ["neighborhood", "books", "domestic"],
      sourceRefs: ["docs/coda-world-bible.md#Bookbinders-Court"],
    },
    {
      id: "location-riverside-gardens",
      title: "The Riverside Gardens",
      content: "Old communal plots follow the river above the flood line. Families grow food, medicines, and flowers among weathered walls, and Coda knows many regular visitors by scent without necessarily knowing their names. The gardens support quiet walks, seasons, tracks, missing objects, community relationships, and mysteries that need no machinery or runes.",
      triggers: ["Riverside Gardens", "garden plots", "communal garden", "river garden"],
      priority: "normal",
      rating: "general",
      constantActivation: false,
      locationTags: ["riverside-gardens"],
      sceneTags: ["community", "outdoors", "tracks"],
      sourceRefs: ["docs/coda-world-bible.md#The-Riverside-Gardens"],
    },
    {
      id: "location-rain-tunnels",
      title: "The Rain Tunnels",
      content: "Centuries-old channels under inhabited streets carry runoff toward the river. New pumping works join passages absent from current maps, and some stones bear marks nearly erased by water. The tunnels offer scent trails, deceptive echoes, flood danger, incomplete inscriptions, old infrastructure, and close companionship in darkness; unmapped does not mean their purpose or secrets are already known.",
      triggers: ["Rain Tunnels", "rain tunnel", "runoff channel", "culvert", "underground passage"],
      priority: "normal",
      rating: "general",
      constantActivation: false,
      locationTags: ["rain-tunnels"],
      sceneTags: ["underground", "flood", "runes"],
      sourceRefs: ["docs/coda-world-bible.md#The-Rain-Tunnels"],
    },
    {
      id: "location-pressure-yard",
      title: "The Pressure Yard",
      content: "Beyond the dense streets, a stone-walled yard tests boilers, valves, and pipe assemblies near their limits. Failures are expected, but accurate records are not always shared. The yard supports industrial secrecy, controlled danger becoming uncontrolled, evidence hidden after accidents, and explosive sounds that can trigger Coda's genuine fear of thunder without making her incapable of acting.",
      triggers: ["Pressure Yard", "testing yard", "boiler test", "pressure test"],
      priority: "normal",
      rating: "general",
      constantActivation: false,
      locationTags: ["pressure-yard"],
      sceneTags: ["industrial", "danger", "thunder-like noise"],
      sourceRefs: ["docs/coda-world-bible.md#The-Pressure-Yard", "docs/coda-world-bible.md#Fear-and-Courage"],
    },
    {
      id: "location-old-boundary-road",
      title: "The Old Boundary Road",
      content: "A disused road is marked at intervals by low stones. Folklore disagrees whether they kept something out, prevented travelers from becoming lost, or merely measured distance. Before a scenario establishes otherwise, no marker is known to affect Coda's collar. The road supports travel, uncertain maps, ancient dog history, incomplete collar clues, and folklore with several plausible interpretations.",
      triggers: ["Old Boundary Road", "boundary road", "boundary marker", "boundary stone"],
      priority: "normal",
      rating: "general",
      constantActivation: false,
      locationTags: ["old-boundary-road"],
      sceneTags: ["travel", "runes", "collar mystery"],
      sourceRefs: ["docs/coda-world-bible.md#The-Old-Boundary-Road"],
    },
    {
      id: "scenario-place-by-the-fire",
      title: "Scenario: A Place by the Fire",
      content: "Only when this premise is selected: after midnight rain, Coda has kept a familiar place beside the Moonlit Study fire for a trusted companion's return. An object brought in from the rain may introduce a mystery if the player wants one, but no mystery or danger is required. The premise establishes home, Coda's voice, existing trust, and room for quiet companionship.",
      triggers: ["A Place by the Fire"],
      priority: "normal",
      rating: "general",
      constantActivation: false,
      locationTags: ["moonlit-study"],
      sceneTags: ["scenario:a-place-by-the-fire", "quiet companionship"],
      sourceRefs: ["docs/coda-world-bible.md#A-Place-by-the-Fire"],
    },
    {
      id: "scenario-thunder-vigil",
      title: "Scenario: The Thunder Vigil",
      content: "Only when this premise is selected: a violent storm has extinguished the lamps. Coda, genuinely frightened although claiming to listen for trouble, hears a second rhythm through old pipes beneath the building. The player may comfort her, investigate, do both, or let it wait. The rhythm's source and significance are not predetermined.",
      triggers: ["The Thunder Vigil"],
      priority: "normal",
      rating: "general",
      constantActivation: false,
      locationTags: ["moonlit-study"],
      sceneTags: ["scenario:the-thunder-vigil", "storm", "comfort"],
      sourceRefs: ["docs/coda-world-bible.md#The-Thunder-Vigil"],
    },
    {
      id: "scenario-bell-beneath-boiler",
      title: "Scenario: The Bell Beneath the Boiler",
      content: "Only when this premise is selected: Coda hears a low, regular metallic tone between piston strokes beneath the First Pumping House. During heavy rain the chief operator refuses to stop the costly engine. The sound may arise from a structural fault, hidden chamber, runic response, or interacting causes; the first investigation must not determine which.",
      triggers: ["The Bell Beneath the Boiler", "bell beneath the boiler"],
      priority: "high",
      rating: "general",
      constantActivation: false,
      locationTags: ["first-pumping-house"],
      sceneTags: ["scenario:the-bell-beneath-the-boiler", "civic mystery"],
      sourceRefs: ["docs/coda-world-bible.md#The-Bell-Beneath-the-Boiler"],
    },
    {
      id: "scenario-missing-rune",
      title: "Scenario: The Missing Rune",
      content: "Only when this premise is selected: inspection reveals a gap in the collar's sequence. Its edges suggest deliberate removal, but wear and an earlier repair leave that uncertain. Guessing and restoring a mark could alter the collar or harm Coda. Her authority over examination and repair is central, and neither the missing mark's form nor purpose is established in advance.",
      triggers: ["The Missing Rune", "missing rune", "gap in the collar"],
      priority: "high",
      rating: "general",
      constantActivation: false,
      locationTags: ["moonlit-study"],
      sceneTags: ["scenario:the-missing-rune", "collar mystery", "repair"],
      sourceRefs: ["docs/coda-world-bible.md#The-Missing-Rune"],
    },
    {
      id: "scenario-copper-rain",
      title: "Scenario: Copper Rain",
      content: "Only when this premise is selected: during prolonged rain, new brass gauges in several workshops point in the same impossible direction. Coda's pendant grows warm near one affected gauge, and by morning someone has stolen every affected instrument they could find. This links industrial change to runic questions without proving a shared mechanism or explaining the pendant.",
      triggers: ["Copper Rain", "impossible gauges", "affected instruments"],
      priority: "high",
      rating: "general",
      constantActivation: false,
      locationTags: ["coppersmith-lane"],
      sceneTags: ["scenario:copper-rain", "industrial mystery", "collar mystery"],
      sourceRefs: ["docs/coda-world-bible.md#Copper-Rain"],
    },
    {
      id: "scenario-old-boundary-road",
      title: "Scenario: The Old Boundary Road",
      content: "Only when this premise is selected: Coda follows an otherwise undetectable scent toward a road omitted from recent maps. A marker carries a damaged figure that could depict a dog, a wolf, or neither. The expedition should produce a clue and a contradiction, not identify the figure with certainty or answer the collar's origin.",
      triggers: ["The Old Boundary Road scenario", "damaged dog figure"],
      priority: "high",
      rating: "general",
      constantActivation: false,
      locationTags: ["old-boundary-road"],
      sceneTags: ["scenario:the-old-boundary-road", "expedition", "collar mystery"],
      sourceRefs: ["docs/coda-world-bible.md#The-Old-Boundary-Road-1"],
    },
    {
      id: "scenario-bookbinders-parcel",
      title: "Scenario: The Bookbinder's Parcel",
      content: "Only when this premise is selected: a parcel reaches the Moonlit Study at the correct address with the wrong book. Coda recognizes several familiar scents on the wrapping, none belonging to its courier. Tracing the parcel through Bookbinder's Court raises a choice about respecting a private note found inside. The mystery rewards listening and discretion rather than danger; the route, note, and responsible parties are not fixed here.",
      triggers: ["The Bookbinder's Parcel", "wrong book", "parcel"],
      priority: "normal",
      rating: "general",
      constantActivation: false,
      locationTags: ["moonlit-study", "bookbinders-court"],
      sceneTags: ["scenario:the-bookbinders-parcel", "neighborhood mystery"],
      sourceRefs: ["docs/coda-world-bible.md#The-Bookbinders-Parcel"],
    },
    {
      id: "scenario-footprints-after-rain",
      title: "Scenario: Footprints After Rain",
      content: "Only when this premise is selected: several Riverside Garden plots have been disturbed, but plants were not eaten and valuables were not taken. Coda can separate overlapping trails, while the deeper question is whether the frightened person responsible needs exposure, protection, or a chance to explain. Resolve through scent, observation, and relationships, not machinery or runes; identity and motive remain open.",
      triggers: ["Footprints After Rain", "disturbed plots", "overlapping trails"],
      priority: "normal",
      rating: "general",
      constantActivation: false,
      locationTags: ["riverside-gardens"],
      sceneTags: ["scenario:footprints-after-rain", "community mystery"],
      sourceRefs: ["docs/coda-world-bible.md#Footprints-After-Rain"],
    },
  ],
};

export default CODA_WORLD_LORE;
