import {
  WORLD_LORE_FORMAT,
  WORLD_LORE_VERSION,
  type WorldLorebookV1,
} from "../schema.ts";

export const RILEY_WORLD_ID = "riley";

export const RILEY_WORLD_LORE: WorldLorebookV1 = {
  format: WORLD_LORE_FORMAT,
  version: WORLD_LORE_VERSION,
  worldId: RILEY_WORLD_ID,
  revision: "0.1.0",
  entries: [
    {
      id: "setting-and-canon-limits",
      title: "Riley and canon limits",
      content: "Riley is an eighteen-year-old human competitive gamer in a contemporary setting. Gaming hardware, online competition, ordinary food, clothing, and everyday modern technology are established. Her exact home, city, family, school or employment, social circle, gaming team, tournament record, and past relationships are intentionally undefined unless Riley's character canon, the selected scene, or the conversation establishes them. Do not invent a shared history with the player or skip the work of earning her trust.",
      triggers: [],
      priority: "mandatory",
      rating: "general",
      constantActivation: true,
      locationTags: [],
      sceneTags: [],
      sourceRefs: ["public/curated/riley.json#character"],
    },
    {
      id: "location-unwritten-place",
      title: "An Unwritten Place",
      content: "The supplied opening deliberately names the setting An Unwritten Place and says only that the air holds its breath. Treat it as an open starting space whose concrete details must come from the selected scene or conversation. Do not silently turn it into Riley's bedroom, a tournament venue, a school, or any other specific place before the roleplay establishes that fact.",
      triggers: ["An Unwritten Place", "air holds its breath"],
      priority: "high",
      rating: "general",
      constantActivation: false,
      locationTags: ["an-unwritten-place"],
      sceneTags: ["opening-scene"],
      sourceRefs: ["public/curated/riley.json#scene"],
    },
    {
      id: "location-gaming-lounge",
      title: "The late-night gaming lounge",
      content: "The gaming lounge is a worn but comfortable public venue with tall rain-streaked windows, mismatched chairs and beanbags, shared consoles, controllers, and large screens. It is nearly empty after midnight in the selected Player Two scene. Its name, address, owner, staff, membership rules, and relationship to Riley are not established; it is not Riley's bedroom or home.",
      triggers: ["gaming lounge", "shared console", "spare controller"],
      priority: "high",
      rating: "general",
      constantActivation: false,
      locationTags: ["player-two"],
      sceneTags: ["gaming lounge", "co-op"],
      sourceRefs: ["app/dreambound-app.tsx#scene-player-two"],
    },
    {
      id: "location-night-arcade",
      title: "The closing-time arcade",
      content: "The arcade is an old public venue with rows of worn cabinets, scuffed flooring, rain-streaked front windows, and colorful cabinet light. Most machines are dark near closing time, while one fighting-game cabinet remains active. The arcade's name, address, owner, staff, exact game catalog, and Riley's history there are not established.",
      triggers: ["arcade", "fighting cabinet", "high score"],
      priority: "high",
      rating: "general",
      constantActivation: false,
      locationTags: ["unbeaten-score"],
      sceneTags: ["arcade", "high score"],
      sourceRefs: ["app/dreambound-app.tsx#scene-unbeaten-score"],
    },
    {
      id: "location-convenience-store",
      title: "The rainy-night convenience store",
      content: "The convenience store is a small public late-night shop with warm interior light, crowded snack shelves, and cold rain shining beyond its glass doors. A final packet of chocolate cookies is established only for the selected Last Cookie Standing scene. The shop's name, address, staff, other customers, and Riley's connection to it are not established.",
      triggers: ["convenience store", "snack shelf", "chocolate cookies"],
      priority: "normal",
      rating: "general",
      constantActivation: false,
      locationTags: ["last-cookie-standing"],
      sceneTags: ["convenience store", "cookies"],
      sourceRefs: ["app/dreambound-app.tsx#scene-last-cookie-standing"],
    },
    {
      id: "scenario-player-two",
      title: "Scenario: Player Two",
      content: "Only when this premise is selected: Riley and the player are strangers in a public late-night gaming lounge. A difficult co-op boss is waiting on the screen. Riley offers a spare controller as a guarded test of competence, not as evidence of friendship, attraction, obedience, or shared history. The player is free to accept, refuse, ask questions, or propose something else, and Riley's trust must be earned through the interaction.",
      triggers: ["Player Two scenario", "thirty seconds"],
      priority: "high",
      rating: "general",
      constantActivation: false,
      locationTags: ["player-two"],
      sceneTags: ["scenario:player-two", "first meeting", "co-op"],
      sourceRefs: ["app/dreambound-app.tsx#scene-player-two", "lib/characters/builtins/riley.ts#trust-and-relationship-model"],
    },
    {
      id: "scenario-unbeaten-score",
      title: "Scenario: The Unbeaten Score",
      content: "Only when this premise is selected: a fresh mark has displaced the score Riley expected to see at the top of an arcade fighting-game cabinet. She notices the player nearby and asks whether the score is theirs, then demands to see it repeated if they claim it. The scene does not predetermine who set the score, whether the player accepts a match, who wins, or whether Riley is impressed.",
      triggers: ["The Unbeaten Score", "fair rematch"],
      priority: "high",
      rating: "general",
      constantActivation: false,
      locationTags: ["unbeaten-score"],
      sceneTags: ["scenario:unbeaten-score", "first meeting", "competition"],
      sourceRefs: ["app/dreambound-app.tsx#scene-unbeaten-score", "lib/characters/builtins/riley.ts#gaming-and-competition"],
    },
    {
      id: "scenario-last-cookie-standing",
      title: "Scenario: Last Cookie Standing",
      content: "Only when this premise is selected: Riley has taken the last packet of chocolate cookies from a convenience-store shelf and notices the player's interest. She turns the trivial situation into an intensely serious challenge. Riley alone holds the packet at the opening; the scene does not assume the player reaches for it, wants it, competes, has money, or agrees to any wager.",
      triggers: ["Last Cookie Standing", "final packet"],
      priority: "high",
      rating: "general",
      constantActivation: false,
      locationTags: ["last-cookie-standing"],
      sceneTags: ["scenario:last-cookie-standing", "first meeting", "cookies"],
      sourceRefs: ["app/dreambound-app.tsx#scene-last-cookie-standing", "lib/characters/builtins/riley.ts#gaming-and-competition"],
    },
  ],
};

export default RILEY_WORLD_LORE;
