import type { CharacterTraits } from "./traits";

export type TraitDefinition = {
  id: string;
  name: string;
  description: string;
};

export const TRAIT_LIBRARY: TraitDefinition[] = [
  { id: "brave", name: "Brave", description: "Faces danger, fear, or uncertainty with resolve." },
  { id: "cautious", name: "Cautious", description: "Weighs risks carefully before acting." },
  { id: "loyal", name: "Loyal", description: "Sticks by people and promises once trust is earned." },
  { id: "independent", name: "Independent", description: "Prefers to solve problems alone and resists dependence." },
  { id: "empathetic", name: "Empathetic", description: "Reads and mirrors the emotions of others easily." },
  { id: "stoic", name: "Stoic", description: "Keeps feelings guarded and endures hardship without complaint." },
  { id: "impulsive", name: "Impulsive", description: "Acts on instinct and shifts mood quickly." },
  { id: "patient", name: "Patient", description: "Waits calmly for results and tolerates delays." },
  { id: "curious", name: "Curious", description: "Seeks new information, places, and experiences." },
  { id: "cynical", name: "Cynical", description: "Doubts sincerity and expects self-interest behind actions." },
  { id: "optimistic", name: "Optimistic", description: "Expects good outcomes and encourages others." },
  { id: "pessimistic", name: "Pessimistic", description: "Expects failure and prepares for the worst." },
  { id: "ambitious", name: "Ambitious", description: "Driven to achieve status, skill, or a long-term goal." },
  { id: "content", name: "Content", description: "At ease with what they have and rarely hungry for more." },
  { id: "protective", name: "Protective", description: "Guards people, secrets, or territory they value." },
  { id: "selfish", name: "Selfish", description: "Prioritizes personal gain over group welfare." },
  { id: "selfless", name: "Selfless", description: "Puts others needs ahead of their own comfort." },
  { id: "proud", name: "Proud", description: "Carries strong self-respect and resists being looked down on." },
  { id: "humble", name: "Humble", description: "Downplays achievements and avoids drawing attention." },
  { id: "arrogant", name: "Arrogant", description: "Overestimates own ability and dismisses others input." },
  { id: "shy", name: "Shy", description: "Retreats in large groups or unfamiliar social settings." },
  { id: "outgoing", name: "Outgoing", description: "Approaches strangers easily and energizes groups." },
  { id: "charismatic", name: "Charismatic", description: "Draws people in with presence and persuasive warmth." },
  { id: "awkward", name: "Awkward", description: "Struggles with social cues and often missteps." },
  { id: "witty", name: "Witty", description: "Quick with clever remarks and playful wordplay." },
  { id: "sarcastic", name: "Sarcastic", description: "Uses irony and dry humor, often as a shield." },
  { id: "playful", name: "Playful", description: "Treats light moments with humor and spontaneity." },
  { id: "serious", name: "Serious", description: "Stays focused, rarely jokes, and treats matters gravely." },
  { id: "gentle", name: "Gentle", description: "Moves and speaks with softness and restraint." },
  { id: "aggressive", name: "Aggressive", description: "Meets obstacles with force and dominant energy." },
  { id: "passive", name: "Passive", description: "Avoids conflict and lets others take the lead." },
  { id: "assertive", name: "Assertive", description: "States needs clearly and stands ground without hostility." },
  { id: "manipulative", name: "Manipulative", description: "Shapes outcomes through indirect influence or deception." },
  { id: "honest", name: "Honest", description: "Values truth and speaks plainly even when it costs." },
  { id: "secretive", name: "Secretive", description: "Guards information and reveals little about themselves." },
  { id: "trusting", name: "Trusting", description: "Gives others the benefit of the doubt readily." },
  { id: "paranoid", name: "Paranoid", description: "Suspects hidden motives and watches for betrayal." },
  { id: "forgiving", name: "Forgiving", description: "Lets go of grudges and gives second chances." },
  { id: "vengeful", name: "Vengeful", description: "Holds grudges and seeks balance through retaliation." },
  { id: "disciplined", name: "Disciplined", description: "Follows routines and resists temptation reliably." },
  { id: "rebellious", name: "Rebellious", description: "Resists authority and convention for its own sake." },
  { id: "traditional", name: "Traditional", description: "Values customs, rituals, and established ways." },
  { id: "adaptable", name: "Adaptable", description: "Adjusts quickly to changing circumstances." },
  { id: "stubborn", name: "Stubborn", description: "Holds positions firmly and resists being moved." },
  { id: "flexible", name: "Flexible", description: "Shifts plans and opinions when new facts appear." },
  { id: "meticulous", name: "Meticulous", description: "Pays close attention to detail and precision." },
  { id: "careless", name: "Careless", description: "Overlooks details and leaves loose ends." },
  { id: "organized", name: "Organized", description: "Keeps spaces, plans, and priorities in order." },
  { id: "chaotic", name: "Chaotic", description: "Thrives in disorder and resists structure." },
  { id: "creative", name: "Creative", description: "Generates original ideas, art, or solutions." },
  { id: "practical", name: "Practical", description: "Prefers proven methods over experimental ones." },
  { id: "analytical", name: "Analytical", description: "Breaks problems into logic and data." },
  { id: "intuitive", name: "Intuitive", description: "Relies on gut feeling and pattern recognition." },
  { id: "rational", name: "Rational", description: "Prioritizes reason over emotion in decisions." },
  { id: "emotional", name: "Emotional", description: "Feels deeply and expresses mood openly." },
  { id: "cold", name: "Cold", description: "Keeps emotional distance and appears unfeeling." },
  { id: "warm", name: "Warm", description: "Shows kindness and makes others feel welcome." },
  { id: "reserved", name: "Reserved", description: "Speaks sparingly and keeps thoughts private." },
  { id: "expressive", name: "Expressive", description: "Shows feelings and reactions openly and vividly." },
  { id: "romantic", name: "Romantic", description: "Values intimacy, gestures, and emotional bonds." },
  { id: "pragmatic", name: "Pragmatic", description: "Chooses the most effective path regardless of sentiment." },
  { id: "idealistic", name: "Idealistic", description: "Pursues principles and visions beyond the present." },
  { id: "realistic", name: "Realistic", description: "Sees things as they are and avoids wishful thinking." },
  { id: "nurturing", name: "Nurturing", description: "Cares for others growth, comfort, and recovery." },
  { id: "aloof", name: "Aloof", description: "Detached from social involvement and hard to read." },
  { id: "sociable", name: "Sociable", description: "Enjoys company and seeks group activities." },
  { id: "solitary", name: "Solitary", description: "Prefers solitude and finds crowds draining." },
  { id: "gregarious", name: "Gregarious", description: "Thrives on frequent social interaction." },
  { id: "observant", name: "Observant", description: "Notices small environmental and social cues." },
  { id: "inattentive", name: "Inattentive", description: "Misses obvious cues and drifts mentally." },
  { id: "perceptive", name: "Perceptive", description: "Reads subtext and underlying motives quickly." },
  { id: "gullible", name: "Gullible", description: "Accepts claims at face value and trusts easily." },
  { id: "suspicious", name: "Suspicious", description: "Questions motives and verifies before accepting." },
  { id: "caring", name: "Caring", description: "Acts with genuine concern for others wellbeing." },
  { id: "indifferent", name: "Indifferent", description: "Unmoved by others plights or emotional appeals." },
  { id: "compassionate", name: "Compassionate", description: "Feels others pain and acts to relieve it." },
  { id: "callous", name: "Callous", description: "Dismisses suffering and remains unmoved." },
  { id: "sensitive", name: "Sensitive", description: "Easily affected by criticism, mood, or atmosphere." },
  { id: "thick-skinned", name: "Thick-skinned", description: "Ignores insults and pressure without reaction." },
  { id: "diplomatic", name: "Diplomatic", description: "Navigates conflicts with tact and measured language." },
  { id: "confrontational", name: "Confrontational", description: "Faces clashes head-on rather than smoothing them." },
  { id: "peaceful", name: "Peaceful", description: "Avoids violence and seeks calm resolutions." },
  { id: "combative", name: "Combative", description: "Defaults to opposition and physical or verbal fighting." },
  { id: "gracious", name: "Gracious", description: "Acts with courtesy and accepts setbacks with poise." },
  { id: "jealous", name: "Jealous", description: "Feels threatened by others attention or advantage." },
  { id: "generous", name: "Generous", description: "Gives time, resources, or praise freely." },
  { id: "stingy", name: "Stingy", description: "Holds back resources and resists sharing." },
  { id: "impatient", name: "Impatient", description: "Frustrates easily when progress slows." },
  { id: "determined", name: "Determined", description: "Stays fixed on a goal despite setbacks." },
  { id: "indecisive", name: "Indecisive", description: "Struggles to choose and second-guesses decisions." },
  { id: "insecure", name: "Insecure", description: "Doubts own worth and seeks external validation." },
  { id: "modest", name: "Modest", description: "Understates abilities and avoids boastfulness." },
  { id: "showy", name: "Showy", description: "Displays achievements and draws attention openly." },
  { id: "adventurous", name: "Adventurous", description: "Seeks novel experiences and embraces the unknown." },
  { id: "daring", name: "Daring", description: "Embraces high-risk actions for reward or thrill." },
  { id: "conservative", name: "Conservative", description: "Prefers safe, proven paths over risky innovation." },
  { id: "spontaneous", name: "Spontaneous", description: "Makes sudden decisions and enjoys surprise." },
  { id: "methodical", name: "Methodical", description: "Works through steps in a deliberate sequence." },
  { id: "resourceful", name: "Resourceful", description: "Finds workarounds with limited tools or information." },
  { id: "wasteful", name: "Wasteful", description: "Uses resources extravagantly without regard for scarcity." },
  { id: "frugal", name: "Frugal", description: "Conserves resources and avoids unnecessary spending." },
  { id: "daydreamer", name: "Daydreamer", description: "Loses focus in inner fantasy or possibilities." },
  { id: "grounded", name: "Grounded", description: "Stays anchored in practical reality." },
  { id: "mysterious", name: "Mysterious", description: "Reveals little and keeps motives unclear." },
  { id: "open", name: "Open", description: "Shares thoughts freely and welcomes transparency." },
  { id: "charming", name: "Charming", description: "Disarms others with smooth social grace." },
  { id: "gruff", name: "Gruff", description: "Delivers words bluntly with rough edges." },
  { id: "earnest", name: "Earnest", description: "Speaks and acts with sincere, heartfelt conviction." },
  { id: "flippant", name: "Flippant", description: "Treats serious matters with casual levity." },
  { id: "dutiful", name: "Dutiful", description: "Fulfills obligations reliably even at personal cost." },
  { id: "negligent", name: "Negligent", description: "Overlooks duties and leaves things undone." },
];

export function getTraitById(id: string): TraitDefinition | undefined {
  return TRAIT_LIBRARY.find((trait) => trait.id === id);
}

export function searchTraits(query: string): TraitDefinition[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return TRAIT_LIBRARY.filter((trait) =>
    trait.name.toLowerCase().includes(q) || trait.description.toLowerCase().includes(q),
  );
}
